"""Write log entries to cloudwatch logs."""

from __future__ import print_function
import logging
import watchtower
import os

log_group = os.getenv('log_group')
log_stream = os.getenv('log_stream')
logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)
aws_handler = watchtower.CloudWatchLogHandler(log_group=log_group, stream_name=log_stream)
logger.addHandler(aws_handler)


def main(event, context):

    try:
        message_source = event['Records'][0]['EventSource']
    except KeyError:
        return

    if message_source == 'aws:sns':
        subject = event['Records'][0]['Sns']['Subject']
        body = event['Records'][0]['Sns']['Message']

        if subject:
            logger.info("{}\n{}".format(subject, body))
        else:
            logger.info(body)

        aws_handler.flush()

    return 'Generated by Lambda'
